# Generated by Django 2.0.10 on 2019-03-17 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('toptenlists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='toptenlist',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toptenlist_created_by_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='toptenlist',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='toptenlist_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='toptenlist',
            name='parent_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_item', to='toptenlists.Item'),
        ),
        migrations.AddField(
            model_name='item',
            name='toptenlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='toptenlists.TopTenList'),
        ),
    ]
