# Generated by Django 2.0.10 on 2019-03-25 09:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('toptenlists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='toptenlist',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topTenList_created_by_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='toptenlist',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topTenList_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='toptenlist',
            name='parent_topTenItem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_topTenItem', to='toptenlists.TopTenItem'),
        ),
        migrations.AddField(
            model_name='toptenitem',
            name='topTenList',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topTenItem', to='toptenlists.TopTenList'),
        ),
    ]
