# Generated by Django 2.0.10 on 2019-08-20 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toptenlists', '0002_auto_20190819_1802'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reusableitem',
            old_name='my_vote',
            new_name='change_request_my_vote',
        ),
        migrations.RenameField(
            model_name='reusableitem',
            old_name='votes_no_count',
            new_name='change_request_votes_no_count',
        ),
        migrations.RenameField(
            model_name='reusableitem',
            old_name='votes_yes_count',
            new_name='change_request_votes_yes_count',
        ),
    ]
