# Generated by Django 3.2.25 on 2026-05-25 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toptenlists', '0002_auto_20190922_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reusableitem',
            name='is_public',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
