# Generated by Django 2.0.10 on 2019-08-29 18:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('toptenlists', '0002_auto_20190829_1803'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('context', models.CharField(blank=True, default='', editable=False, max_length=255)),
                ('event', models.CharField(blank=True, default='', editable=False, max_length=5000)),
                ('unread', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='notification_created_by', to=settings.AUTH_USER_MODEL)),
                ('reusableItem', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reusableItem', to='toptenlists.ReusableItem')),
            ],
        ),
    ]
