# Generated by Django 2.0.10 on 2019-05-22 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('toptenlists', '0003_auto_20190509_1636'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReusableItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255)),
                ('definition', models.CharField(blank=True, default='', max_length=255)),
                ('link', models.CharField(blank=True, default='', max_length=255)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('users_when_modified', models.IntegerField(default=0)),
                ('votes_yes', django_mysql.models.JSONField(default=dict)),
                ('votes_no', django_mysql.models.JSONField(default=dict)),
                ('proposed_modification', django_mysql.models.JSONField(default=dict)),
                ('history', django_mysql.models.JSONField(default=dict)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reusableItem_created_by', to=settings.AUTH_USER_MODEL)),
                ('proposed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reusableItem_proposed_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='toptenitem',
            name='reusableItem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reusableItem', to='toptenlists.ReusableItem'),
        ),
    ]
