# Generated by Django 2.0.10 on 2019-09-16 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toptenlists', '0003_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='topTenItem',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topTenItem', to='toptenlists.TopTenItem'),
        ),
    ]
