# Generated by Django 2.0.10 on 2019-09-20 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toptenlists', '0004_notification_toptenitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reusableitem',
            name='users_when_modified',
        ),
    ]
