# Generated by Django 2.0.10 on 2019-05-22 14:05

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('toptenlists', '0004_auto_20190522_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reusableitem',
            name='proposed_modification',
            field=django_mysql.models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='reusableitem',
            name='votes_no',
            field=django_mysql.models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='reusableitem',
            name='votes_yes',
            field=django_mysql.models.JSONField(default=list),
        ),
    ]
