# Generated by Django 2.0.10 on 2019-09-20 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toptenlists', '0005_remove_reusableitem_users_when_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='new',
            field=models.BooleanField(default=True),
        ),
    ]
