# Generated by Django 2.0.10 on 2019-05-22 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('toptenlists', '0006_auto_20190522_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reusableitem',
            name='history',
            field=django_mysql.models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='reusableitem',
            name='proposed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reusableItem_proposed_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reusableitem',
            name='proposed_modification',
            field=django_mysql.models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='reusableitem',
            name='votes_no',
            field=django_mysql.models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='reusableitem',
            name='votes_yes',
            field=django_mysql.models.JSONField(blank=True, default=list),
        ),
    ]
