# Generated by Django 2.0.10 on 2019-08-08 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toptenlists', '0012_reusableitem_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='reusableitem',
            name='created_by_username',
            field=models.CharField(default='lsdj', max_length=255),
            preserve_default=False,
        ),
    ]
