# Generated by Django 2.0.10 on 2019-08-12 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toptenlists', '0013_reusableitem_created_by_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='reusableitem',
            name='proposed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
