# Generated by Django 2.0.10 on 2019-08-12 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toptenlists', '0014_reusableitem_proposed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reusableitem',
            name='proposed_at',
            field=models.DateTimeField(null=True),
        ),
    ]
