# Generated by Django 2.0.10 on 2019-08-12 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toptenlists', '0015_auto_20190812_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reusableitem',
            name='proposed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
