# Generated by Django 2.0.10 on 2019-08-13 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toptenlists', '0016_auto_20190812_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='reusableitem',
            name='votes_yes_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
