# Generated by Django 2.0.10 on 2019-08-13 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toptenlists', '0017_reusableitem_votes_yes_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='reusableitem',
            name='my_vote',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reusableitem',
            name='votes_no_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
