# Generated by Django 2.0.10 on 2019-08-14 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toptenlists', '0020_auto_20190813_1859'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reusableitem',
            old_name='proposed_modification',
            new_name='change_request',
        ),
    ]
