# Generated by Django 2.0.10 on 2019-08-28 16:39

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='notifications',
            field=django_mysql.models.JSONField(blank=True, default=list),
        ),
    ]
